### ISSUE TITLE
Documentation error on `karafka-testing` example

### ISSUE THREAD

**Issue by hbontempo-cw** [karafka/wiki#25]
First of all: create gen. Love working with karafka.

I think I found an error on a rakafka-testing` example.
https://github.com/karafka/wiki/blob/62335a8619b351afa0d520517f825c23875c18c3/Testing.md?plain=1#L126

Apparently `Karafka::Routing::Topic` has a method `#find`.

Change suggestion:
```diff
-  let(:topic) { group.topics.find { |ts| ts.name == 'xml_data' } } 
+  let(:topic) { group.topics.find('xml_data' ) }

**Comment by mensfeld** [comment]
It's not an error as find is also supported because block based is part of the enumerable, though I do agree it could be better.

**Comment by mensfeld** [comment]
Updated. Thank you.
