### ISSUE TITLE
Document config AJ details + LRJ/VP + combo

### ISSUE THREAD

**Issue by mensfeld** [karafka/wiki#8]
ref https://github.com/karafka/karafka/issues/798

**Comment by whithajess** [comment]
Just to add to this - I think It would be great to document a similar feature list to those adapters directly in [ActiveJob Queue Adapters](https://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html).

```
|                   | Async | Queues | Delayed    | Priorities | Timeout | Retries |
|-------------------|-------|--------|------------|------------|---------|---------|
| Backburner        | Yes   | Yes    | Yes        | Yes        | Job     | Global  |
| Delayed Job       | Yes   | Yes    | Yes        | Job        | Global  | Global  |
| Que               | Yes   | Yes    | Yes        | Job        | No      | Job     |
| queue_classic     | Yes   | Yes    | Yes*       | No         | No      | No      |
| Resque            | Yes   | Yes    | Yes (Gem)  | Queue      | Global  | Yes     |
| Sidekiq           | Yes   | Yes    | Yes        | Queue      | No      | Job     |
| Sneakers          | Yes   | Yes    | No         | Queue      | Queue   | No      |
| Sucker Punch      | Yes   | Yes    | Yes        | No         | No      | No      |
| Active Job Async  | Yes   | Yes    | Yes        | No         | No      | No      |
| Active Job Inline | No    | Yes    | N/A        | N/A        | N/A     | N/A     |
```

My understanding from what I have read so far is it would look like this:
|                   | Async | Queues | Delayed    | Priorities | Timeout | Retries |
|-------------------|-------|--------|------------|------------|---------|---------|
| Karafka        | Yes   | Yes    | No        | No        | No     | No  |

**Comment by mensfeld** [comment]
@whithajess in Rails itself I cannot as they no longer accept PRs for new adapters. 

Also, don't you think we have retries? ;) Upon crash Karafka will retry the job based on the retry policies

**Comment by whithajess** [comment]
> @whithajess in Rails itself I cannot as they no longer accept PRs for new adapters. 
> 
> Also, don't you think we have retries? ;) Upon crash Karafka will retry the job based on the retry policies

No just in the ActiveJob documentation you are writing.

I didn't think it was configurable other than the back off?

> Job: The number of retries can be set per instance of the job class.
> 
> Yes: The Number of retries can be configured globally, for each instance or on the queue. This adapter may also present failed instances of the job class that can be restarted.
> 
> Global: The adapter has a global number of retries.
> 
> No: The adapter does not allow the number of retries to be configured.
>  N/A: The adapter does not run in a separate process, and therefore doesn't support retries.

**Comment by mensfeld** [comment]
Ah ok. I thought you meant a general retries policy. The AJ jobs yes, no retries of theirs on that one.

**Comment by mensfeld** [comment]
AJ and VP are documented.
